// @generated by protobuf-ts 2.9.3 with parameter add_pb_suffix,client_grpc1,generate_dependencies,keep_enum_prefix,ts_nocheck,use_proto_field_name
// @generated from protobuf file "vald/v1/vald/filter.proto" (package "vald.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
//
// Copyright (C) 2019-2023 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//
import { Upsert_MultiObjectRequest } from "../payload/payload_pb";
import { Upsert_ObjectRequest } from "../payload/payload_pb";
import { Update_MultiObjectRequest } from "../payload/payload_pb";
import { Update_ObjectRequest } from "../payload/payload_pb";
import { Object_Locations } from "../payload/payload_pb";
import { Insert_MultiObjectRequest } from "../payload/payload_pb";
import { Object_StreamLocation } from "../payload/payload_pb";
import { Object_Location } from "../payload/payload_pb";
import { Insert_ObjectRequest } from "../payload/payload_pb";
import { Search_StreamResponse } from "../payload/payload_pb";
import { Search_Responses } from "../payload/payload_pb";
import { Search_MultiObjectRequest } from "../payload/payload_pb";
import { Search_Response } from "../payload/payload_pb";
import { Search_ObjectRequest } from "../payload/payload_pb";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service vald.v1.Filter
 */
export const Filter = new ServiceType("vald.v1.Filter", [
    { name: "SearchObject", options: { "google.api.http": { post: "/search/object", body: "*" } }, I: Search_ObjectRequest, O: Search_Response },
    { name: "MultiSearchObject", options: { "google.api.http": { post: "/search/object/multiple", body: "*" } }, I: Search_MultiObjectRequest, O: Search_Responses },
    { name: "StreamSearchObject", serverStreaming: true, clientStreaming: true, options: {}, I: Search_ObjectRequest, O: Search_StreamResponse },
    { name: "InsertObject", options: { "google.api.http": { post: "/insert/object", body: "*" } }, I: Insert_ObjectRequest, O: Object_Location },
    { name: "StreamInsertObject", serverStreaming: true, clientStreaming: true, options: {}, I: Insert_ObjectRequest, O: Object_StreamLocation },
    { name: "MultiInsertObject", options: { "google.api.http": { post: "/insert/object/multiple", body: "*" } }, I: Insert_MultiObjectRequest, O: Object_Locations },
    { name: "UpdateObject", options: { "google.api.http": { post: "/update/object", body: "*" } }, I: Update_ObjectRequest, O: Object_Location },
    { name: "StreamUpdateObject", serverStreaming: true, clientStreaming: true, options: {}, I: Update_ObjectRequest, O: Object_StreamLocation },
    { name: "MultiUpdateObject", options: { "google.api.http": { post: "/update/object/multiple", body: "*" } }, I: Update_MultiObjectRequest, O: Object_Locations },
    { name: "UpsertObject", options: { "google.api.http": { post: "/upsert/object", body: "*" } }, I: Upsert_ObjectRequest, O: Object_Location },
    { name: "StreamUpsertObject", serverStreaming: true, clientStreaming: true, options: {}, I: Upsert_ObjectRequest, O: Object_StreamLocation },
    { name: "MultiUpsertObject", options: { "google.api.http": { post: "/upsert/object/multiple", body: "*" } }, I: Upsert_MultiObjectRequest, O: Object_Locations }
]);
