/* eslint-disable */
// @generated by protobuf-ts 2.9.3 with parameter add_pb_suffix,client_grpc1,generate_dependencies,keep_enum_prefix,ts_nocheck,use_proto_field_name,output_javascript,output_legacy_commonjs,eslint_disable
// @generated from protobuf file "vald/v1/vald/filter.proto" (package "vald.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
//
// Copyright (C) 2019-2023 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Filter = void 0;
/* eslint-disable */
// @generated by protobuf-ts 2.9.3 with parameter add_pb_suffix,client_grpc1,generate_dependencies,keep_enum_prefix,ts_nocheck,use_proto_field_name,output_javascript,output_legacy_commonjs,eslint_disable
// @generated from protobuf file "vald/v1/vald/filter.proto" (package "vald.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
//
// Copyright (C) 2019-2023 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//
const payload_pb_1 = require("../payload/payload_pb");
const payload_pb_2 = require("../payload/payload_pb");
const payload_pb_3 = require("../payload/payload_pb");
const payload_pb_4 = require("../payload/payload_pb");
const payload_pb_5 = require("../payload/payload_pb");
const payload_pb_6 = require("../payload/payload_pb");
const payload_pb_7 = require("../payload/payload_pb");
const payload_pb_8 = require("../payload/payload_pb");
const payload_pb_9 = require("../payload/payload_pb");
const payload_pb_10 = require("../payload/payload_pb");
const payload_pb_11 = require("../payload/payload_pb");
const payload_pb_12 = require("../payload/payload_pb");
const payload_pb_13 = require("../payload/payload_pb");
const payload_pb_14 = require("../payload/payload_pb");
const runtime_rpc_1 = require("@protobuf-ts/runtime-rpc");
/**
 * @generated ServiceType for protobuf service vald.v1.Filter
 */
exports.Filter = new runtime_rpc_1.ServiceType("vald.v1.Filter", [
    { name: "SearchObject", options: { "google.api.http": { post: "/search/object", body: "*" } }, I: payload_pb_14.Search_ObjectRequest, O: payload_pb_13.Search_Response },
    { name: "MultiSearchObject", options: { "google.api.http": { post: "/search/object/multiple", body: "*" } }, I: payload_pb_12.Search_MultiObjectRequest, O: payload_pb_11.Search_Responses },
    { name: "StreamSearchObject", serverStreaming: true, clientStreaming: true, options: {}, I: payload_pb_14.Search_ObjectRequest, O: payload_pb_10.Search_StreamResponse },
    { name: "InsertObject", options: { "google.api.http": { post: "/insert/object", body: "*" } }, I: payload_pb_9.Insert_ObjectRequest, O: payload_pb_8.Object_Location },
    { name: "StreamInsertObject", serverStreaming: true, clientStreaming: true, options: {}, I: payload_pb_9.Insert_ObjectRequest, O: payload_pb_7.Object_StreamLocation },
    { name: "MultiInsertObject", options: { "google.api.http": { post: "/insert/object/multiple", body: "*" } }, I: payload_pb_6.Insert_MultiObjectRequest, O: payload_pb_5.Object_Locations },
    { name: "UpdateObject", options: { "google.api.http": { post: "/update/object", body: "*" } }, I: payload_pb_4.Update_ObjectRequest, O: payload_pb_8.Object_Location },
    { name: "StreamUpdateObject", serverStreaming: true, clientStreaming: true, options: {}, I: payload_pb_4.Update_ObjectRequest, O: payload_pb_7.Object_StreamLocation },
    { name: "MultiUpdateObject", options: { "google.api.http": { post: "/update/object/multiple", body: "*" } }, I: payload_pb_3.Update_MultiObjectRequest, O: payload_pb_5.Object_Locations },
    { name: "UpsertObject", options: { "google.api.http": { post: "/upsert/object", body: "*" } }, I: payload_pb_2.Upsert_ObjectRequest, O: payload_pb_8.Object_Location },
    { name: "StreamUpsertObject", serverStreaming: true, clientStreaming: true, options: {}, I: payload_pb_2.Upsert_ObjectRequest, O: payload_pb_7.Object_StreamLocation },
    { name: "MultiUpsertObject", options: { "google.api.http": { post: "/upsert/object/multiple", body: "*" } }, I: payload_pb_1.Upsert_MultiObjectRequest, O: payload_pb_5.Object_Locations }
]);
