/* eslint-disable */
// @generated by protobuf-ts 2.9.3 with parameter add_pb_suffix,client_grpc1,generate_dependencies,keep_enum_prefix,ts_nocheck,use_proto_field_name,output_javascript,output_legacy_commonjs,eslint_disable
// @generated from protobuf file "vald/v1/vald/filter.proto" (package "vald.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
//
// Copyright (C) 2019-2023 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { Upsert_MultiObjectRequest } from "../payload/payload_pb";
import type { Upsert_ObjectRequest } from "../payload/payload_pb";
import type { Update_MultiObjectRequest } from "../payload/payload_pb";
import type { Update_ObjectRequest } from "../payload/payload_pb";
import type { Object_Locations } from "../payload/payload_pb";
import type { Insert_MultiObjectRequest } from "../payload/payload_pb";
import type { Object_StreamLocation } from "../payload/payload_pb";
import type { Object_Location } from "../payload/payload_pb";
import type { Insert_ObjectRequest } from "../payload/payload_pb";
import type { Search_StreamResponse } from "../payload/payload_pb";
import type { Search_Responses } from "../payload/payload_pb";
import type { Search_MultiObjectRequest } from "../payload/payload_pb";
import type { Search_Response } from "../payload/payload_pb";
import type { Search_ObjectRequest } from "../payload/payload_pb";
import * as grpc from "@grpc/grpc-js";
/**
 * Filter service provides ways to connect to Vald through filter.
 *
 * @generated from protobuf service vald.v1.Filter
 */
export interface IFilterClient {
    /**
     * A method to search object.
     *
     * @generated from protobuf rpc: SearchObject(payload.v1.Search.ObjectRequest) returns (payload.v1.Search.Response);
     */
    searchObject(input: Search_ObjectRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Search_Response) => void): grpc.ClientUnaryCall;
    searchObject(input: Search_ObjectRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Search_Response) => void): grpc.ClientUnaryCall;
    searchObject(input: Search_ObjectRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Search_Response) => void): grpc.ClientUnaryCall;
    searchObject(input: Search_ObjectRequest, callback: (err: grpc.ServiceError | null, value?: Search_Response) => void): grpc.ClientUnaryCall;
    /**
     * A method to search multiple objects.
     *
     * @generated from protobuf rpc: MultiSearchObject(payload.v1.Search.MultiObjectRequest) returns (payload.v1.Search.Responses);
     */
    multiSearchObject(input: Search_MultiObjectRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Search_Responses) => void): grpc.ClientUnaryCall;
    multiSearchObject(input: Search_MultiObjectRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Search_Responses) => void): grpc.ClientUnaryCall;
    multiSearchObject(input: Search_MultiObjectRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Search_Responses) => void): grpc.ClientUnaryCall;
    multiSearchObject(input: Search_MultiObjectRequest, callback: (err: grpc.ServiceError | null, value?: Search_Responses) => void): grpc.ClientUnaryCall;
    /**
     * A method to search object by bidirectional streaming.
     *
     * @generated from protobuf rpc: StreamSearchObject(stream payload.v1.Search.ObjectRequest) returns (stream payload.v1.Search.StreamResponse);
     */
    streamSearchObject(metadata: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientDuplexStream<Search_ObjectRequest, Search_StreamResponse>;
    streamSearchObject(options?: grpc.CallOptions): grpc.ClientDuplexStream<Search_ObjectRequest, Search_StreamResponse>;
    /**
     * A method insert object.
     *
     * @generated from protobuf rpc: InsertObject(payload.v1.Insert.ObjectRequest) returns (payload.v1.Object.Location);
     */
    insertObject(input: Insert_ObjectRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Object_Location) => void): grpc.ClientUnaryCall;
    insertObject(input: Insert_ObjectRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Object_Location) => void): grpc.ClientUnaryCall;
    insertObject(input: Insert_ObjectRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Object_Location) => void): grpc.ClientUnaryCall;
    insertObject(input: Insert_ObjectRequest, callback: (err: grpc.ServiceError | null, value?: Object_Location) => void): grpc.ClientUnaryCall;
    /**
     * Represent the streaming RPC to insert object by bidirectional streaming.
     *
     * @generated from protobuf rpc: StreamInsertObject(stream payload.v1.Insert.ObjectRequest) returns (stream payload.v1.Object.StreamLocation);
     */
    streamInsertObject(metadata: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientDuplexStream<Insert_ObjectRequest, Object_StreamLocation>;
    streamInsertObject(options?: grpc.CallOptions): grpc.ClientDuplexStream<Insert_ObjectRequest, Object_StreamLocation>;
    /**
     * A method to insert multiple objects.
     *
     * @generated from protobuf rpc: MultiInsertObject(payload.v1.Insert.MultiObjectRequest) returns (payload.v1.Object.Locations);
     */
    multiInsertObject(input: Insert_MultiObjectRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Object_Locations) => void): grpc.ClientUnaryCall;
    multiInsertObject(input: Insert_MultiObjectRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Object_Locations) => void): grpc.ClientUnaryCall;
    multiInsertObject(input: Insert_MultiObjectRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Object_Locations) => void): grpc.ClientUnaryCall;
    multiInsertObject(input: Insert_MultiObjectRequest, callback: (err: grpc.ServiceError | null, value?: Object_Locations) => void): grpc.ClientUnaryCall;
    /**
     * A method to update object.
     *
     * @generated from protobuf rpc: UpdateObject(payload.v1.Update.ObjectRequest) returns (payload.v1.Object.Location);
     */
    updateObject(input: Update_ObjectRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Object_Location) => void): grpc.ClientUnaryCall;
    updateObject(input: Update_ObjectRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Object_Location) => void): grpc.ClientUnaryCall;
    updateObject(input: Update_ObjectRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Object_Location) => void): grpc.ClientUnaryCall;
    updateObject(input: Update_ObjectRequest, callback: (err: grpc.ServiceError | null, value?: Object_Location) => void): grpc.ClientUnaryCall;
    /**
     * A method to update object by bidirectional streaming.
     *
     * @generated from protobuf rpc: StreamUpdateObject(stream payload.v1.Update.ObjectRequest) returns (stream payload.v1.Object.StreamLocation);
     */
    streamUpdateObject(metadata: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientDuplexStream<Update_ObjectRequest, Object_StreamLocation>;
    streamUpdateObject(options?: grpc.CallOptions): grpc.ClientDuplexStream<Update_ObjectRequest, Object_StreamLocation>;
    /**
     * A method to update multiple objects.
     *
     * @generated from protobuf rpc: MultiUpdateObject(payload.v1.Update.MultiObjectRequest) returns (payload.v1.Object.Locations);
     */
    multiUpdateObject(input: Update_MultiObjectRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Object_Locations) => void): grpc.ClientUnaryCall;
    multiUpdateObject(input: Update_MultiObjectRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Object_Locations) => void): grpc.ClientUnaryCall;
    multiUpdateObject(input: Update_MultiObjectRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Object_Locations) => void): grpc.ClientUnaryCall;
    multiUpdateObject(input: Update_MultiObjectRequest, callback: (err: grpc.ServiceError | null, value?: Object_Locations) => void): grpc.ClientUnaryCall;
    /**
     * A method to upsert object.
     *
     * @generated from protobuf rpc: UpsertObject(payload.v1.Upsert.ObjectRequest) returns (payload.v1.Object.Location);
     */
    upsertObject(input: Upsert_ObjectRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Object_Location) => void): grpc.ClientUnaryCall;
    upsertObject(input: Upsert_ObjectRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Object_Location) => void): grpc.ClientUnaryCall;
    upsertObject(input: Upsert_ObjectRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Object_Location) => void): grpc.ClientUnaryCall;
    upsertObject(input: Upsert_ObjectRequest, callback: (err: grpc.ServiceError | null, value?: Object_Location) => void): grpc.ClientUnaryCall;
    /**
     * A method to upsert object by bidirectional streaming.
     *
     * @generated from protobuf rpc: StreamUpsertObject(stream payload.v1.Upsert.ObjectRequest) returns (stream payload.v1.Object.StreamLocation);
     */
    streamUpsertObject(metadata: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientDuplexStream<Upsert_ObjectRequest, Object_StreamLocation>;
    streamUpsertObject(options?: grpc.CallOptions): grpc.ClientDuplexStream<Upsert_ObjectRequest, Object_StreamLocation>;
    /**
     * A method to upsert multiple objects.
     *
     * @generated from protobuf rpc: MultiUpsertObject(payload.v1.Upsert.MultiObjectRequest) returns (payload.v1.Object.Locations);
     */
    multiUpsertObject(input: Upsert_MultiObjectRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Object_Locations) => void): grpc.ClientUnaryCall;
    multiUpsertObject(input: Upsert_MultiObjectRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Object_Locations) => void): grpc.ClientUnaryCall;
    multiUpsertObject(input: Upsert_MultiObjectRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Object_Locations) => void): grpc.ClientUnaryCall;
    multiUpsertObject(input: Upsert_MultiObjectRequest, callback: (err: grpc.ServiceError | null, value?: Object_Locations) => void): grpc.ClientUnaryCall;
}
/**
 * Filter service provides ways to connect to Vald through filter.
 *
 * @generated from protobuf service vald.v1.Filter
 */
export declare class FilterClient extends grpc.Client implements IFilterClient {
    private readonly _binaryOptions;
    constructor(address: string, credentials: grpc.ChannelCredentials, options?: grpc.ClientOptions, binaryOptions?: Partial<BinaryReadOptions & BinaryWriteOptions>);
    /**
     * A method to search object.
     *
     * @generated from protobuf rpc: SearchObject(payload.v1.Search.ObjectRequest) returns (payload.v1.Search.Response);
     */
    searchObject(input: Search_ObjectRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Search_Response) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Search_Response) => void), callback?: ((err: grpc.ServiceError | null, value?: Search_Response) => void)): grpc.ClientUnaryCall;
    /**
     * A method to search multiple objects.
     *
     * @generated from protobuf rpc: MultiSearchObject(payload.v1.Search.MultiObjectRequest) returns (payload.v1.Search.Responses);
     */
    multiSearchObject(input: Search_MultiObjectRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Search_Responses) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Search_Responses) => void), callback?: ((err: grpc.ServiceError | null, value?: Search_Responses) => void)): grpc.ClientUnaryCall;
    /**
     * A method to search object by bidirectional streaming.
     *
     * @generated from protobuf rpc: StreamSearchObject(stream payload.v1.Search.ObjectRequest) returns (stream payload.v1.Search.StreamResponse);
     */
    streamSearchObject(metadata?: grpc.Metadata | grpc.CallOptions, options?: grpc.CallOptions): grpc.ClientDuplexStream<Search_ObjectRequest, Search_StreamResponse>;
    /**
     * A method insert object.
     *
     * @generated from protobuf rpc: InsertObject(payload.v1.Insert.ObjectRequest) returns (payload.v1.Object.Location);
     */
    insertObject(input: Insert_ObjectRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Object_Location) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Object_Location) => void), callback?: ((err: grpc.ServiceError | null, value?: Object_Location) => void)): grpc.ClientUnaryCall;
    /**
     * Represent the streaming RPC to insert object by bidirectional streaming.
     *
     * @generated from protobuf rpc: StreamInsertObject(stream payload.v1.Insert.ObjectRequest) returns (stream payload.v1.Object.StreamLocation);
     */
    streamInsertObject(metadata?: grpc.Metadata | grpc.CallOptions, options?: grpc.CallOptions): grpc.ClientDuplexStream<Insert_ObjectRequest, Object_StreamLocation>;
    /**
     * A method to insert multiple objects.
     *
     * @generated from protobuf rpc: MultiInsertObject(payload.v1.Insert.MultiObjectRequest) returns (payload.v1.Object.Locations);
     */
    multiInsertObject(input: Insert_MultiObjectRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Object_Locations) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Object_Locations) => void), callback?: ((err: grpc.ServiceError | null, value?: Object_Locations) => void)): grpc.ClientUnaryCall;
    /**
     * A method to update object.
     *
     * @generated from protobuf rpc: UpdateObject(payload.v1.Update.ObjectRequest) returns (payload.v1.Object.Location);
     */
    updateObject(input: Update_ObjectRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Object_Location) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Object_Location) => void), callback?: ((err: grpc.ServiceError | null, value?: Object_Location) => void)): grpc.ClientUnaryCall;
    /**
     * A method to update object by bidirectional streaming.
     *
     * @generated from protobuf rpc: StreamUpdateObject(stream payload.v1.Update.ObjectRequest) returns (stream payload.v1.Object.StreamLocation);
     */
    streamUpdateObject(metadata?: grpc.Metadata | grpc.CallOptions, options?: grpc.CallOptions): grpc.ClientDuplexStream<Update_ObjectRequest, Object_StreamLocation>;
    /**
     * A method to update multiple objects.
     *
     * @generated from protobuf rpc: MultiUpdateObject(payload.v1.Update.MultiObjectRequest) returns (payload.v1.Object.Locations);
     */
    multiUpdateObject(input: Update_MultiObjectRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Object_Locations) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Object_Locations) => void), callback?: ((err: grpc.ServiceError | null, value?: Object_Locations) => void)): grpc.ClientUnaryCall;
    /**
     * A method to upsert object.
     *
     * @generated from protobuf rpc: UpsertObject(payload.v1.Upsert.ObjectRequest) returns (payload.v1.Object.Location);
     */
    upsertObject(input: Upsert_ObjectRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Object_Location) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Object_Location) => void), callback?: ((err: grpc.ServiceError | null, value?: Object_Location) => void)): grpc.ClientUnaryCall;
    /**
     * A method to upsert object by bidirectional streaming.
     *
     * @generated from protobuf rpc: StreamUpsertObject(stream payload.v1.Upsert.ObjectRequest) returns (stream payload.v1.Object.StreamLocation);
     */
    streamUpsertObject(metadata?: grpc.Metadata | grpc.CallOptions, options?: grpc.CallOptions): grpc.ClientDuplexStream<Upsert_ObjectRequest, Object_StreamLocation>;
    /**
     * A method to upsert multiple objects.
     *
     * @generated from protobuf rpc: MultiUpsertObject(payload.v1.Upsert.MultiObjectRequest) returns (payload.v1.Object.Locations);
     */
    multiUpsertObject(input: Upsert_MultiObjectRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Object_Locations) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Object_Locations) => void), callback?: ((err: grpc.ServiceError | null, value?: Object_Locations) => void)): grpc.ClientUnaryCall;
}
