//
// Copyright (C) 2019-2023 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// @generated by protoc-gen-connect-es v1.2.0
// @generated from file vald/v1/vald/filter.proto (package vald.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Insert_MultiObjectRequest, Insert_ObjectRequest, Object_Location, Object_Locations, Object_StreamLocation, Search_MultiObjectRequest, Search_ObjectRequest, Search_Response, Search_Responses, Search_StreamResponse, Update_MultiObjectRequest, Update_ObjectRequest, Upsert_MultiObjectRequest, Upsert_ObjectRequest } from "../payload/payload_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Filter service provides ways to connect to Vald through filter.
 *
 * @generated from service vald.v1.Filter
 */
export const Filter = {
  typeName: "vald.v1.Filter",
  methods: {
    /**
     * A method to search object.
     *
     * @generated from rpc vald.v1.Filter.SearchObject
     */
    searchObject: {
      name: "SearchObject",
      I: Search_ObjectRequest,
      O: Search_Response,
      kind: MethodKind.Unary,
    },
    /**
     * A method to search multiple objects.
     *
     * @generated from rpc vald.v1.Filter.MultiSearchObject
     */
    multiSearchObject: {
      name: "MultiSearchObject",
      I: Search_MultiObjectRequest,
      O: Search_Responses,
      kind: MethodKind.Unary,
    },
    /**
     * A method to search object by bidirectional streaming.
     *
     * @generated from rpc vald.v1.Filter.StreamSearchObject
     */
    streamSearchObject: {
      name: "StreamSearchObject",
      I: Search_ObjectRequest,
      O: Search_StreamResponse,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * A method insert object.
     *
     * @generated from rpc vald.v1.Filter.InsertObject
     */
    insertObject: {
      name: "InsertObject",
      I: Insert_ObjectRequest,
      O: Object_Location,
      kind: MethodKind.Unary,
    },
    /**
     * Represent the streaming RPC to insert object by bidirectional streaming.
     *
     * @generated from rpc vald.v1.Filter.StreamInsertObject
     */
    streamInsertObject: {
      name: "StreamInsertObject",
      I: Insert_ObjectRequest,
      O: Object_StreamLocation,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * A method to insert multiple objects.
     *
     * @generated from rpc vald.v1.Filter.MultiInsertObject
     */
    multiInsertObject: {
      name: "MultiInsertObject",
      I: Insert_MultiObjectRequest,
      O: Object_Locations,
      kind: MethodKind.Unary,
    },
    /**
     * A method to update object.
     *
     * @generated from rpc vald.v1.Filter.UpdateObject
     */
    updateObject: {
      name: "UpdateObject",
      I: Update_ObjectRequest,
      O: Object_Location,
      kind: MethodKind.Unary,
    },
    /**
     * A method to update object by bidirectional streaming.
     *
     * @generated from rpc vald.v1.Filter.StreamUpdateObject
     */
    streamUpdateObject: {
      name: "StreamUpdateObject",
      I: Update_ObjectRequest,
      O: Object_StreamLocation,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * A method to update multiple objects.
     *
     * @generated from rpc vald.v1.Filter.MultiUpdateObject
     */
    multiUpdateObject: {
      name: "MultiUpdateObject",
      I: Update_MultiObjectRequest,
      O: Object_Locations,
      kind: MethodKind.Unary,
    },
    /**
     * A method to upsert object.
     *
     * @generated from rpc vald.v1.Filter.UpsertObject
     */
    upsertObject: {
      name: "UpsertObject",
      I: Upsert_ObjectRequest,
      O: Object_Location,
      kind: MethodKind.Unary,
    },
    /**
     * A method to upsert object by bidirectional streaming.
     *
     * @generated from rpc vald.v1.Filter.StreamUpsertObject
     */
    streamUpsertObject: {
      name: "StreamUpsertObject",
      I: Upsert_ObjectRequest,
      O: Object_StreamLocation,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * A method to upsert multiple objects.
     *
     * @generated from rpc vald.v1.Filter.MultiUpsertObject
     */
    multiUpsertObject: {
      name: "MultiUpsertObject",
      I: Upsert_MultiObjectRequest,
      O: Object_Locations,
      kind: MethodKind.Unary,
    },
  }
};

