/* eslint-disable */
// @generated by protobuf-ts 2.10.0 with parameter add_pb_suffix,client_grpc1,generate_dependencies,keep_enum_prefix,ts_nocheck,use_proto_field_name,output_javascript,output_legacy_commonjs,eslint_disable
// @generated from protobuf file "vald/v1/vald/index.proto" (package "vald.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
//
// Copyright (C) 2019-2025 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { Info_Index_PropertyDetail } from "../payload/payload_pb";
import type { Info_Index_StatisticsDetail } from "../payload/payload_pb";
import type { Info_Index_Statistics } from "../payload/payload_pb";
import type { Info_Index_Detail } from "../payload/payload_pb";
import type { Info_Index_Count } from "../payload/payload_pb";
import type { Empty } from "../payload/payload_pb";
import * as grpc from "@grpc/grpc-js";
/**
 * Overview
 * Represent the index manager service.
 *
 * @generated from protobuf service vald.v1.Index
 */
export interface IIndexClient {
    /**
     * Overview
     * Represent the RPC to get the index information.
     *
     * @generated from protobuf rpc: IndexInfo(payload.v1.Empty) returns (payload.v1.Info.Index.Count);
     */
    indexInfo(input: Empty, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Info_Index_Count) => void): grpc.ClientUnaryCall;
    indexInfo(input: Empty, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Info_Index_Count) => void): grpc.ClientUnaryCall;
    indexInfo(input: Empty, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Info_Index_Count) => void): grpc.ClientUnaryCall;
    indexInfo(input: Empty, callback: (err: grpc.ServiceError | null, value?: Info_Index_Count) => void): grpc.ClientUnaryCall;
    /**
     * Overview
     * Represent the RPC to get the index information for each agents.
     *
     * @generated from protobuf rpc: IndexDetail(payload.v1.Empty) returns (payload.v1.Info.Index.Detail);
     */
    indexDetail(input: Empty, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Info_Index_Detail) => void): grpc.ClientUnaryCall;
    indexDetail(input: Empty, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Info_Index_Detail) => void): grpc.ClientUnaryCall;
    indexDetail(input: Empty, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Info_Index_Detail) => void): grpc.ClientUnaryCall;
    indexDetail(input: Empty, callback: (err: grpc.ServiceError | null, value?: Info_Index_Detail) => void): grpc.ClientUnaryCall;
    /**
     * Overview
     * Represent the RPC to get the index statistics.
     *
     * @generated from protobuf rpc: IndexStatistics(payload.v1.Empty) returns (payload.v1.Info.Index.Statistics);
     */
    indexStatistics(input: Empty, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Info_Index_Statistics) => void): grpc.ClientUnaryCall;
    indexStatistics(input: Empty, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Info_Index_Statistics) => void): grpc.ClientUnaryCall;
    indexStatistics(input: Empty, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Info_Index_Statistics) => void): grpc.ClientUnaryCall;
    indexStatistics(input: Empty, callback: (err: grpc.ServiceError | null, value?: Info_Index_Statistics) => void): grpc.ClientUnaryCall;
    /**
     * Overview
     * Represent the RPC to get the index statistics for each agents.
     *
     * @generated from protobuf rpc: IndexStatisticsDetail(payload.v1.Empty) returns (payload.v1.Info.Index.StatisticsDetail);
     */
    indexStatisticsDetail(input: Empty, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Info_Index_StatisticsDetail) => void): grpc.ClientUnaryCall;
    indexStatisticsDetail(input: Empty, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Info_Index_StatisticsDetail) => void): grpc.ClientUnaryCall;
    indexStatisticsDetail(input: Empty, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Info_Index_StatisticsDetail) => void): grpc.ClientUnaryCall;
    indexStatisticsDetail(input: Empty, callback: (err: grpc.ServiceError | null, value?: Info_Index_StatisticsDetail) => void): grpc.ClientUnaryCall;
    /**
     * Overview
     * Represent the RPC to get the index property.
     *
     * @generated from protobuf rpc: IndexProperty(payload.v1.Empty) returns (payload.v1.Info.Index.PropertyDetail);
     */
    indexProperty(input: Empty, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Info_Index_PropertyDetail) => void): grpc.ClientUnaryCall;
    indexProperty(input: Empty, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Info_Index_PropertyDetail) => void): grpc.ClientUnaryCall;
    indexProperty(input: Empty, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Info_Index_PropertyDetail) => void): grpc.ClientUnaryCall;
    indexProperty(input: Empty, callback: (err: grpc.ServiceError | null, value?: Info_Index_PropertyDetail) => void): grpc.ClientUnaryCall;
}
/**
 * Overview
 * Represent the index manager service.
 *
 * @generated from protobuf service vald.v1.Index
 */
export declare class IndexClient extends grpc.Client implements IIndexClient {
    private readonly _binaryOptions;
    constructor(address: string, credentials: grpc.ChannelCredentials, options?: grpc.ClientOptions, binaryOptions?: Partial<BinaryReadOptions & BinaryWriteOptions>);
    /**
     * Overview
     * Represent the RPC to get the index information.
     *
     * @generated from protobuf rpc: IndexInfo(payload.v1.Empty) returns (payload.v1.Info.Index.Count);
     */
    indexInfo(input: Empty, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Info_Index_Count) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Info_Index_Count) => void), callback?: ((err: grpc.ServiceError | null, value?: Info_Index_Count) => void)): grpc.ClientUnaryCall;
    /**
     * Overview
     * Represent the RPC to get the index information for each agents.
     *
     * @generated from protobuf rpc: IndexDetail(payload.v1.Empty) returns (payload.v1.Info.Index.Detail);
     */
    indexDetail(input: Empty, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Info_Index_Detail) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Info_Index_Detail) => void), callback?: ((err: grpc.ServiceError | null, value?: Info_Index_Detail) => void)): grpc.ClientUnaryCall;
    /**
     * Overview
     * Represent the RPC to get the index statistics.
     *
     * @generated from protobuf rpc: IndexStatistics(payload.v1.Empty) returns (payload.v1.Info.Index.Statistics);
     */
    indexStatistics(input: Empty, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Info_Index_Statistics) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Info_Index_Statistics) => void), callback?: ((err: grpc.ServiceError | null, value?: Info_Index_Statistics) => void)): grpc.ClientUnaryCall;
    /**
     * Overview
     * Represent the RPC to get the index statistics for each agents.
     *
     * @generated from protobuf rpc: IndexStatisticsDetail(payload.v1.Empty) returns (payload.v1.Info.Index.StatisticsDetail);
     */
    indexStatisticsDetail(input: Empty, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Info_Index_StatisticsDetail) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Info_Index_StatisticsDetail) => void), callback?: ((err: grpc.ServiceError | null, value?: Info_Index_StatisticsDetail) => void)): grpc.ClientUnaryCall;
    /**
     * Overview
     * Represent the RPC to get the index property.
     *
     * @generated from protobuf rpc: IndexProperty(payload.v1.Empty) returns (payload.v1.Info.Index.PropertyDetail);
     */
    indexProperty(input: Empty, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Info_Index_PropertyDetail) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Info_Index_PropertyDetail) => void), callback?: ((err: grpc.ServiceError | null, value?: Info_Index_PropertyDetail) => void)): grpc.ClientUnaryCall;
}
