// @generated by protobuf-ts 2.9.3 with parameter add_pb_suffix,client_grpc1,generate_dependencies,keep_enum_prefix,ts_nocheck,use_proto_field_name
// @generated from protobuf file "vald/v1/vald/insert.proto" (package "vald.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
//
// Copyright (C) 2019-2023 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//
import { Object_Locations } from "../payload/payload_pb";
import { Insert_MultiRequest } from "../payload/payload_pb";
import { Object_StreamLocation } from "../payload/payload_pb";
import { Object_Location } from "../payload/payload_pb";
import { Insert_Request } from "../payload/payload_pb";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service vald.v1.Insert
 */
export const Insert = new ServiceType("vald.v1.Insert", [
    { name: "Insert", options: { "google.api.http": { post: "/insert", body: "*" } }, I: Insert_Request, O: Object_Location },
    { name: "StreamInsert", serverStreaming: true, clientStreaming: true, options: {}, I: Insert_Request, O: Object_StreamLocation },
    { name: "MultiInsert", options: { "google.api.http": { post: "/insert/multiple", body: "*" } }, I: Insert_MultiRequest, O: Object_Locations }
]);
