// @generated by protobuf-ts 2.9.3 with parameter add_pb_suffix,client_grpc1,generate_dependencies,keep_enum_prefix,ts_nocheck,use_proto_field_name
// @generated from protobuf file "vald/v1/vald/search.proto" (package "vald.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
//
// Copyright (C) 2019-2023 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//
import { Search_MultiIDRequest } from "../payload/payload_pb";
import { Search_Responses } from "../payload/payload_pb";
import { Search_MultiRequest } from "../payload/payload_pb";
import { Search_StreamResponse } from "../payload/payload_pb";
import { Search_IDRequest } from "../payload/payload_pb";
import { Search_Response } from "../payload/payload_pb";
import { Search_Request } from "../payload/payload_pb";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service vald.v1.Search
 */
export const Search = new ServiceType("vald.v1.Search", [
    { name: "Search", options: { "google.api.http": { post: "/search", body: "*" } }, I: Search_Request, O: Search_Response },
    { name: "SearchByID", options: { "google.api.http": { post: "/search/id", body: "*" } }, I: Search_IDRequest, O: Search_Response },
    { name: "StreamSearch", serverStreaming: true, clientStreaming: true, options: {}, I: Search_Request, O: Search_StreamResponse },
    { name: "StreamSearchByID", serverStreaming: true, clientStreaming: true, options: {}, I: Search_IDRequest, O: Search_StreamResponse },
    { name: "MultiSearch", options: { "google.api.http": { post: "/search/multiple", body: "*" } }, I: Search_MultiRequest, O: Search_Responses },
    { name: "MultiSearchByID", options: { "google.api.http": { post: "/search/id/multiple", body: "*" } }, I: Search_MultiIDRequest, O: Search_Responses },
    { name: "LinearSearch", options: { "google.api.http": { post: "/linearsearch", body: "*" } }, I: Search_Request, O: Search_Response },
    { name: "LinearSearchByID", options: { "google.api.http": { post: "/linearsearch/id", body: "*" } }, I: Search_IDRequest, O: Search_Response },
    { name: "StreamLinearSearch", serverStreaming: true, clientStreaming: true, options: {}, I: Search_Request, O: Search_StreamResponse },
    { name: "StreamLinearSearchByID", serverStreaming: true, clientStreaming: true, options: {}, I: Search_IDRequest, O: Search_StreamResponse },
    { name: "MultiLinearSearch", options: { "google.api.http": { post: "/linearsearch/multiple", body: "*" } }, I: Search_MultiRequest, O: Search_Responses },
    { name: "MultiLinearSearchByID", options: { "google.api.http": { post: "/linearsearch/id/multiple", body: "*" } }, I: Search_MultiIDRequest, O: Search_Responses }
]);
