// @generated by protobuf-ts 2.9.3 with parameter add_pb_suffix,client_grpc1,generate_dependencies,keep_enum_prefix,ts_nocheck,use_proto_field_name
// @generated from protobuf file "vald/v1/vald/update.proto" (package "vald.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
//
// Copyright (C) 2019-2023 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//
import { Object_Locations } from "../payload/payload_pb";
import { Update_MultiRequest } from "../payload/payload_pb";
import { Object_StreamLocation } from "../payload/payload_pb";
import { Object_Location } from "../payload/payload_pb";
import { Update_Request } from "../payload/payload_pb";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service vald.v1.Update
 */
export const Update = new ServiceType("vald.v1.Update", [
    { name: "Update", options: { "google.api.http": { post: "/update", body: "*" } }, I: Update_Request, O: Object_Location },
    { name: "StreamUpdate", serverStreaming: true, clientStreaming: true, options: {}, I: Update_Request, O: Object_StreamLocation },
    { name: "MultiUpdate", options: { "google.api.http": { post: "/update/multiple", body: "*" } }, I: Update_MultiRequest, O: Object_Locations }
]);
