//
// Copyright (C) 2019-2023 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// @generated by protoc-gen-connect-es v1.2.0
// @generated from file vald/v1/agent/core/agent.proto (package core.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Control_CreateIndexRequest, Empty, Info_Index_Count, Object_GetTimestampRequest, Object_Timestamp } from "../../payload/payload_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Represent the agent service.
 *
 * @generated from service core.v1.Agent
 */
export declare const Agent: {
  readonly typeName: "core.v1.Agent",
  readonly methods: {
    /**
     * Represent the creating index RPC.
     *
     * @generated from rpc core.v1.Agent.CreateIndex
     */
    readonly createIndex: {
      readonly name: "CreateIndex",
      readonly I: typeof Control_CreateIndexRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Represent the saving index RPC.
     *
     * @generated from rpc core.v1.Agent.SaveIndex
     */
    readonly saveIndex: {
      readonly name: "SaveIndex",
      readonly I: typeof Empty,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Represent the creating and saving index RPC.
     *
     * @generated from rpc core.v1.Agent.CreateAndSaveIndex
     */
    readonly createAndSaveIndex: {
      readonly name: "CreateAndSaveIndex",
      readonly I: typeof Control_CreateIndexRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Represent the RPC to get the agent index information.
     *
     * @generated from rpc core.v1.Agent.IndexInfo
     */
    readonly indexInfo: {
      readonly name: "IndexInfo",
      readonly I: typeof Empty,
      readonly O: typeof Info_Index_Count,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Represent the RPC to get the vector metadata. This RPC is mainly used for index correction process
     *
     * @generated from rpc core.v1.Agent.GetTimestamp
     */
    readonly getTimestamp: {
      readonly name: "GetTimestamp",
      readonly I: typeof Object_GetTimestampRequest,
      readonly O: typeof Object_Timestamp,
      readonly kind: MethodKind.Unary,
    },
  }
};

